name: beads-integration
description: "Integrate BMAD sprint planning with Beads/Bd issue tracking system - sync stories to Beads issues"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated
implementation_artifacts: "{config_source}:implementation_artifacts"
planning_artifacts: "{config_source}:planning_artifacts"
output_folder: "{implementation_artifacts}"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/sprint-planning/beads-integration"
instructions: "{installed_path}/instructions.md"

# Variables and inputs
variables:
  # Sprint status file (output from sprint-planning workflow)
  sprint_status_file: "{implementation_artifacts}/sprint-status.yaml"

  # Beads configuration
  beads_config_path: "{project-root}/.beads/config.yaml"
  beads_db_path: "{project-root}/.beads/beads.db"

  # Integration state file
  integration_state_file: "{implementation_artifacts}/beads-integration-state.yaml"

  # Project identification
  project_name: "{config_source}:project_name"

  # Sync mode
  sync_mode: "bidirectional" # Options: bidirectional, bmad-to-beads, beads-to-bmad

# Smart input file references
input_file_patterns:
  sprint_status:
    description: "Sprint status file with all stories and their current status"
    whole: "{implementation_artifacts}/sprint-status.yaml"
    load_strategy: "FULL_LOAD"

# Output configuration
default_output_file: "{integration_state_file}"

standalone: true
